PRODUCT_CREATED = 'Product created successfully!'
INVALID_DATA = 'Please check the product data and try again.'
ALL_PRODUCTS = 'Products of the current user.'
PRODUCT = 'Here is the product for your request.'
PRODUCT_UPDATED = 'Product updated successfully.'
PRODUCT_DELETED = 'Product deleted successfully.'