REGISTRATION_SUCCESS = 'Successfully registered. Please confirm your email.'
CONFIRMATION_MAIL_SENT = 'Confirmation Mail Sent Successfully!'
ACCOUNT_CONFIRMED = 'Account confirmed Successfully. Now you can login!'
LOGIN_SUCCESS = 'Successfully logged in.'
INVALID_DATA = 'Please check the data and Try again...'
INVALID_CONFIRMATION_TOKEN = 'Token Invalid. Please get another confirmation link!'
ACCOUNT_NOT_FOUND = 'Account Not Found.'
WAIT_TO_GET_CONFIRMATION_MAIL = 'Please wait for few minutes and try again...!'
