ALL_RETAILERS = 'Here is the list of all Retailers.'
LOCATIONS_FOR_A_RETAILER = 'Here are the locations for the requested Retailer.'
PRODUCTS_FOR_A_LOCATION = 'Here are the products for the requested Location.'
PRODUCT_NOT_EXIST_IN_THE_LOCATION = 'Product doesn\'t exist in the given Location.'
TOO_MUCH_QUANTITY = 'Given quantity is greater than the availability.'
PURCHASE_SUCCESSFUL = 'Purchase successfully processed.'
INVALID_DATA = 'Please check the data and Try again.'
